### ISSUE TITLE
raster interaction 

### ISSUE THREAD

**Issue by valeriodeluca** [PowerPan/leaflet.mouseCoordinate#1]
Hello Johannes, eb,

I write to ask you some advices about interection with raster data I loaded on leaflet map on my server, such as DEM (Digital Elevation Model).
For example I'd like click to know the elevation value of a specific clicked point.
This plugin would be very useful if I can modify it to use to get elevation value from raster instead coordinate values.

Thanks so much
Best
Valerio

**Comment by valeriodeluca** [comment]
I think the best way is Zoo Project able to create WPS.
Best
Valerio

**Comment by wattnpapa** [comment]
Gernerally that should not be the Problem, if you have an api where you can send the lat/lng and the delivers you an altitude. 
But i am not sure if this project is the right place for it
