### ISSUE TITLE
Not working with Leaflet 1.0.2

### ISSUE THREAD

**Issue by BetterOffDev** [PowerPan/leaflet.mouseCoordinate#11]
I originally had this working with an older version of Leaflet (< 1.0). After upgrading, the plugin doesn't seem to work.

**Comment by wattnpapa** [comment]
ok can you provide me an Javascript Error from the console log?

**Comment by BetterOffDev** [comment]
There was no console error. It just stopped attaching itself to the DOM. You couldn't find the mouse position element anywhere in the DOM. 

The plugin was part of a React component. Nothing changed with how it was imported. The only change was the Leaflet version.
