### ISSUE TITLE
I am having problems in Chrome

### ISSUE THREAD

**Issue by olivierfischer** [PowerPan/leaflet.mouseCoordinate#12]
I cannot get this plugin   to run in Version 55.0.2883.87 m of Chrome on Windows 7.
Can anybody?

Thanks,
Olivier

**Comment by wattnpapa** [comment]
I already know that there is a Problem
I am working in this

Von meinem iPhone gesendet

**Comment by michaelarice** [comment]
I cannot get the plugin to work in Chrome 57.0.2987.110 on OS X 10.11; it works in Safari and Firefox.

**Comment by wattnpapa** [comment]
should now be fixed
