### ISSUE TITLE
UTM/MGRS/USNG zone exceptions

### ISSUE THREAD

**Issue by mtfurlan** [PowerPan/leaflet.mouseCoordinate#2]
This plugin isn't accounting for the exceptions in UTM/USNG/MGRS zones.
https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Exceptions

**Comment by wattnpapa** [comment]
Yes, you are right these Exceptions are not included at the moment. Fell free to "Fix it" and make a pull request ;)
Thx for contributing

**Comment by mtfurlan** [comment]
So my solution would be to replace all of your UTM and UMT->MGRS/USNG code with code from https://github.com/proj4js/mgrs as they don't export the UTM conversion code, so just using it as a dependency would not fix the UTM points.
I think the license solution would just be add all the names in from their MIT, and to include the license thing they have at the bottom of their readme on this one.
Sound reasonable?

**Comment by wattnpapa** [comment]
Hm... i Think it is enough to intigrate this here:

https://github.com/proj4js/mgrs/blob/master/mgrs.js#L128-L147

**Comment by mtfurlan** [comment]
Yeah, you're right, sorry. I just didn't want to look too closely at how it worked...
Do you want the pull request to include updated docs and dist? I didn't change anything that effects the docs, looks like they were just out of date.

**Comment by mtfurlan** [comment]
Okay, I have two other things that could be different pull requests if you want to separate them: adding an example page, and adding an option to hide the extra GPS formats.
Just tell me how you want the pull request(s) to look.

**Comment by wattnpapa** [comment]
Ok @mtfurlan if have created additonale Issues
I am a friend of sperating Ideas from my point of view it is a cleaner view

**Comment by wattnpapa** [comment]
Fixed in #6
